### ISSUE TITLE
OSX sierra java dependency

### ISSUE THREAD

**Issue by papower1** [konlpy/konlpy#121]
OSX sierra에서 konlpy.tag.{Hannanum, Kkma, Komoran, Twitter)의 생성자 호출시 아래와 같은 메세지와 함께 정상 동작하지 않습니다. 디펜던시가 있다는 사항을 문서로 작성하면 좋을 것 같습니다.

![2016-12-08 15 35 04](https://cloud.githubusercontent.com/assets/6247953/21000092/2a88b9b4-bd5c-11e6-9c24-13921b46ba21.png)

그리고 메세지를 따라 자바를 설치한 후 실행하였을 때 아래와 같이 오류가 발생하였습니다.

```
>>> from konlpy.tag import Hannanum
>>> t = Hannanum()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/konlpy/tag/_hannanum.py", line 103, in __init__
    jvm.init_jvm(jvmpath)
  File "/usr/local/lib/python2.7/site-packages/konlpy/jvm.py", line 51, in init_jvm
    '-ea', '-Xmx768m')
  File "/usr/local/lib/python2.7/site-packages/jpype/_core.py", line 50, in startJVM
    _jpype.startup(jvm, tuple(args), True)
RuntimeError: Unable to load DLL [/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Libraries/libjvm.dylib], error = dlopen(/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Libraries/libjvm.dylib, 9): no suitable image found.  Did find:
	/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Libraries/libjvm.dylib: mach-o, but wrong architecture at native/common/include/jp_platform_linux.h:45
>>>
```

**Comment by e9t** [comment]
https://github.com/konlpy/konlpy/issues/115 를 참고해주시기 바랍니다.
