### ISSUE TITLE
ImportError: /home/winter/anaconda2/lib/python2.7/site-packages/_jpype.so: undefined symbol: _ZTVNSt7 에러

### ISSUE THREAD

**Issue by ssun123** [konlpy/konlpy#122]
File "<stdin>", line 1, in <module>
  File "/home/winter/anaconda2/lib/python2.7/site-packages/konlpy/__init__.py", line 15, in <module>
    from . import tag
  File "/home/winter/anaconda2/lib/python2.7/site-packages/konlpy/tag/__init__.py", line 4, in <module>
    from ._hannanum import Hannanum
  File "/home/winter/anaconda2/lib/python2.7/site-packages/konlpy/tag/_hannanum.py", line 7, in <module>
    import jpype
  File "/home/winter/anaconda2/lib/python2.7/site-packages/jpype/__init__.py", line 17, in <module>
    from ._jpackage import *
  File "/home/winter/anaconda2/lib/python2.7/site-packages/jpype/_jpackage.py", line 18, in <module>
    import _jpype
ImportError: /home/winter/anaconda2/lib/python2.7/site-packages/_jpype.so: undefined symbol: _ZTVNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE

설치후 테스트를 위해 python에 
를 입력하니 위와 같은 에러가 떳습니다.
너무 초보적인 질문 인것 같지만 검색해도 답이 나오지 않아 올려봅니다.
OS는 Ubuntu 16.04 python2.7버젼입니다
답변 부탁드려요~

**Comment by jaeho-kang** [comment]
저도 비슷한 오류가 나오네요 .

ubuntu 16.04 
jdk : java 1.7(oracle) 입니다. 

Traceback (most recent call last):
  File "knlpytest.py", line 6, in <module>
    from konlpy.tag import Kkma
  File "/usr/local/anaconda2/lib/python2.7/site-packages/konlpy/__init__.py", line 15, in <module>
    from . import tag
  File "/usr/local/anaconda2/lib/python2.7/site-packages/konlpy/tag/__init__.py", line 4, in <module>
    from ._hannanum import Hannanum
  File "/usr/local/anaconda2/lib/python2.7/site-packages/konlpy/tag/_hannanum.py", line 7, in <module>
    import jpype
  File "/usr/local/anaconda2/lib/python2.7/site-packages/jpype/__init__.py", line 17, in <module>
    from ._jpackage import *
  File "/usr/local/anaconda2/lib/python2.7/site-packages/jpype/_jpackage.py", line 18, in <module>
    import _jpype
ImportError: /usr/local/anaconda2/lib/python2.7/site-packages/_jpype.so: undefined symbol: _ZSt24__throw_out_of_range_fmtPKcz

**Comment by jaeho-kang** [comment]
jpype 문제 해결 되었습니다. 감사합니다. ^^

**Comment by jaeho-kang** [comment]
anaconda python을 이용하여 konlpy를 사용시 발생합니다. 
우선 시스템 기본 python에 있는 jpype와 anaconda의 jpype를 삭제 합니다. 

sudo pip uninstall jpype
/usr/local/anaconda/bin/pip uninstall jpype 

그리고 jpype를 apt-get으로 설치 합니다. 

sudo apt-get install python-jpype

그리고 난후 jpype를 테스트 합니다. 

sudo python -c "import jpype"
위의 코드가 오류 없이 넘어 가면 시스템의  python은 정상입니다. 

그리고 anaconda python에 jpype를 설치 합니다. 
/usr/local/anaconda/bin/pip install jpype1

그리고 anacoda python에서 테스트 합니다. 
/usr/local/anaconda/bin/python -c "import jpype" 
위 코드에서 임포트 오류가 발생하면 

anaconda에서 설치한 jpype 라이브러리에서 오류가 발생한것입니다. 

시스템 python에 설치된 라이브러리 파일을 덮어 쓰면 오류가 해결 됩니다. 

시스템에서 라이버러리를 찾으면 

sudo find / -name _jpype.so
[sudo] password for nuri:
/usr/lib/python2.7/dist-packages/_jpype.so
/usr/lib/pyshared/python2.7/_jpype.so
/usr/local/anaconda2/lib/python2.7/site-packages/_jpype.so 

위와 같이 세개가 나오는데(사용자 환경에 따라 다릅니다.)
/usr/lib/python2.7/dist-packages/_jpype.so <- 이 파일을 
/usr/local/anaconda2/lib/python2.7/site-packages/_jpype.so <- 여기에 덮어 쓰면
해결 됩니다. 

이 방법은 제 개인적인 방법인데 잘 안되면 질의를 올려주시면 도와 드리겠습니다.

**Comment by wwtBlog** [comment]
please use english sb!

**Comment by bongster** [comment]
@wwtBlog what is the meaning of sb?? i don't grasp what you mean

**Comment by Madity** [comment]
@jaeho-kang worked! Thanks :)
