### ISSUE TITLE
Hannanum 사용시 아무런 결과가 도출되지 않고, 경로 에러가 나타남

### ISSUE THREAD

**Issue by PinkWink** [konlpy/konlpy#123]
code)
`from konlpy.tag import Hannanum

hannanum = Hannanum()

print(hannanum.analyze(u'롯데마트의 흑마늘 양념 치킨이 논란이 되고 있다.'))
`
java.io.FileNotFoundException: C:\Program%20Files\Anaconda3\Lib\site-packages\konlpy\java\conf\plugin\MajorPlugin\MorphAnalyzer\ChartMorphAnalyzer.json (지정된 경로를 찾을 수 없습니다)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at java.io.FileReader.<init>(FileReader.java:58)
        at kr.ac.kaist.swrc.jhannanum.share.JSONReader.<init>(JSONReader.java:48)
        at kr.ac.kaist.swrc.jhannanum.plugin.MajorPlugin.MorphAnalyzer.ChartMorphAnalyzer.ChartMorphAnalyzer.initialize(ChartMorphAnalyzer.java:176)
        at kr.ac.kaist.swrc.jhannanum.hannanum.Workflow.activateWorkflow(Workflow.java:421)
        at kr.lucypark.jhannanum.comm.HannanumInterface.morphAnalyzer(HannanumInterface.java:28)

**Comment by PinkWink** [comment]
Anaconda 4.2 버젼을 사용중이었는데...
Anaconda 4.1.1로 내리니 에러가 사라지고 정상 동작을 합니다.
(이유는모르겠습니다.ㅠㅠ)
그리고.. 소중히 잘 사용하고있습니다. 감사합니다.^^
