### ISSUE TITLE
Jpype 에러...

### ISSUE THREAD

**Issue by rudvlf0413** [konlpy/konlpy#147]
우분투 14.10에 anaconda python 3.6 버전을 사용하고 있습니다

from konlpy.tag import Twitter까지는 잘 되는데
t = Twitter() 을 실행하면

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rudvlf0413/anaconda3/lib/python3.6/site-packages/konlpy/tag/_twitter.py", line 71, in __init__
    if not jpype.isJVMStarted():
AttributeError: module 'jpype' has no attribute 'isJVMStarted'

다음과 같은 에러가 뜹니다.
왜 이런걸까요 ㅠㅠㅠ pip install Jpype1을 통해 jpype를 설치한 상태입니다.

**Comment by rudvlf0413** [comment]
해결했습니다
JPype1-py3==0.5.5.2 로 설치하고
conda install libgcc를 설치하니 되더라구요
