### ISSUE TITLE
pyinstaller 활용시 konlpy가 포함되지 않는 문제..

### ISSUE THREAD

**Issue by jooniis** [konlpy/konlpy#149]
안녕하세요?
konlpy 잘 활용하고 있습니다^^

다름 아니라..
gui 프로그램을 만들어보기 위해 pyqt와 pyinstaller를 활용하고 있는데요,
pyinstaller로 실행파일을 만들어 실행할 경우
아래와 같은 오류가 발생하네요..
pyinstaller에서 생성된 폴더의 내용을 봐도.. konlpy 관련 파일은 보이지 않아 패키지가 포함되지 않은 것은 아닌가라는 생각이 드는데요.. 혹시 해결 방법이 없을지요?

=========================================
PS D:\pyinstall\dist\project51_0609> ./project51_0609
Traceback (most recent call last):
  File "site-packages\konlpy\tag\_komoran.py", line 81, in __init__
  File "site-packages\jpype\_jpackage.py", line 60, in __call__
TypeError: Package kr.lucypark.komoran.KomoranInterface is not Callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "project51_0609.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "c:\python3.5\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "cluster.py", line 5, in <module>
  File "site-packages\konlpy\tag\_komoran.py", line 83, in __init__
OSError: Cannot access komoran-dic. Please leave an issue at https://github.com/konlpy/konlpy/issues
Failed to execute script project51_0609

**Comment by songsb13** [comment]
Pyinstaller 를 사용하신다면

spec 파일의 datas에 파일을 추가해보세요!

datas=[("파이썬경로/Python35-32/Lib/site-packages/konlpy/*", "./konlpy"), ("파이썬경로/Python35-32/Lib/site-packages/konlpy/java/*", "./konlpy/java"), ("파이썬경로/Python35-32/Lib/site-packages/konlpy/data/tagset/*", "./konlpy/data/tagset"),],

이걸로 해결했습니다.

**Comment by josungman** [comment]
감사합니다!! 해결되었어요
