### ISSUE TITLE
pyinstaller로 빌드 시 에러

### ISSUE THREAD

**Issue by songsb13** [konlpy/konlpy#154]
```
Traceback (most recent call last):
  File "site-packages\flask\app.py", line 1982, in wsgi_app
  File "site-packages\flask\app.py", line 1614, in full_dispatch_request
  File "site-packages\flask\app.py", line 1517, in handle_user_exception
  File "site-packages\flask\_compat.py", line 33, in reraise
  File "site-packages\flask\app.py", line 1612, in full_dispatch_request
  File "site-packages\flask\app.py", line 1598, in dispatch_request
  File "APIServer.py", line 12, in get_keyword
  File "TextMiner.py", line 9, in mine_keyword
  File "site-packages\konlpy\tag\_kkma.py", line 91, in __init__
  File "site-packages\jpype\_jpackage.py", line 60, in __call__
TypeError: Package kr.lucypark.kkma.KkmaInterface is not Callable
```

위의 에러가 pyinstaller로 exe 제작했을 때 나타나는 에러입니다.

windows 10 (64bit) 사용중인데 32bit에 배포해야해서

python 3.5 32bit
java 1.8.0_141 32bit
konlpy 0.4.4 32bit
JPype1‑0.6.2‑cp35‑cp35m‑win32.whl

등등 모두 32bit로 깔아 python으로는 정상작동합니다.

JAVA_HOME 도 32비트 자바를 사용하도록 바꿨고요.

어떤걸 시도해봐야할까요?

**Comment by songsb13** [comment]
Pyinstaller 를 사용하신다면

spec 파일의 datas에 파일을 추가해보세요!

datas=[("파이썬경로/Python35-32/Lib/site-packages/konlpy/*", "./konlpy"), ("파이썬경로/Python35-32/Lib/site-packages/konlpy/java/*", "./konlpy/java"), ("파이썬경로/Python35-32/Lib/site-packages/konlpy/data/tagset/*", "./konlpy/data/tagset"),],

이걸로 해결했습니다.
