### ISSUE TITLE
kkma = Kkma() 에서 오류가 나면서 이후 진행이 되지 않는 문제

### ISSUE THREAD

**Issue by Gyu-Ho** [konlpy/konlpy#162]
안녕하세요?
JPype 1과 KoNLPy를 순서대로 설치하고 python을 실행한 다음 KoNLPy 홈페이지 첫 화면에 나온대로 명령어를 따라 써 보았는데, 아래와 같은 에러 메시지가 뜨면서 더 이상 진행이 되질 않습니다:

SHINGyuhos-MacBook-Pro:~ Gyu-ho_Shin_Alex$ python
Python 2.7.10 (default, Jul 14 2015, 19:46:27) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from konlpy.tag import Kkma
>>> kkma = Kkma()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/konlpy/tag/_kkma.py", line 91, in __init__
    self.jki = KkmaInterfaceJavaClass()  # Java instance
  File "/Library/Python/2.7/site-packages/jpype/_jpackage.py", line 60, in __call__
    raise TypeError("Package {0} is not Callable".format(self.__name))
TypeError: Package kr.lucypark.kkma.KkmaInterface is not Callable

현재 저는 python 2.7.10을 Mac Yosemite (ver 10.10.5)에서 쓰고 있습니다. 혹시 default python에 문제가 있나 싶어 Canopy와 python 3.6에서도 확인해보았는데, 역시 오류가 납니다. 무엇이 문제일지 말씀해 주실 분 계실지요?

**Comment by DataSoccer** [comment]
/Users/kookbal/Downloads/programing/ml_dl_real/bin/python /Users/kookbal/programing/ml_dl_real/konlpy_test.py
Traceback (most recent call last):
  File "/Users/kookbal/programing/ml_dl_real/konlpy_test.py", line 2, in <module>
    kkma = Kkma()
  File "/Users/kookbal/Downloads/programing/ml_dl_real/lib/python3.6/site-packages/konlpy/tag/_kkma.py", line 91, in __init__
    self.jki = KkmaInterfaceJavaClass()  # Java instance
  File "/Users/kookbal/Downloads/programing/ml_dl_real/lib/python3.6/site-packages/jpype/_jpackage.py", line 60, in __call__
    raise TypeError("Package {0} is not Callable".format(self.__name))
TypeError: Package kr.lucypark.kkma.KkmaInterface is not Callable

Process finished with exit code 1

OSX high Siera
Python 3.6
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
