### ISSUE TITLE
mecab으로 트레이닝 했을시 에러가 나옵니다.

### ISSUE THREAD

**Issue by kih1024** [konlpy/konlpy#191]
안녕하세요.
제가 현재 django를 통해서 챗봇을 만들고 있습니다.
교육 시키는 과정에서 mecab을 썻을시 다음과 에러가 나타납니다.

Traceback (most recent call last):
  File "train.py", line 243, in <module>
    train_cnn()
  File "train.py", line 44, in train_cnn
    x = np.array(list(vocab_processor.fit_transform(x_raw)))  # !
  File "/home/ailab4/Django/myvenv/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/preprocessing/text.py", line 188, in fit_transform
    self.fit(raw_documents)
  File "/home/ailab4/Django/myvenv/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/preprocessing/text.py", line 170, in fit
    for tokens in self._tokenizer(raw_documents):
SystemError: <built-in function delete_Tagger> returned a result with an error set

mecab 쓰기전 twitter 태그 패키지를 썻을때는 정상적으로 교육이 되던것이 mecab으로 바꾸니 위와 같은 에러가 뜹니다. 구글링 해도 잘 안나오고 이유를 잘 모르겠습니다. 이거에 대해서 조금이라도 아시는분은 조언 부탁드립니다.

**Comment by ho9science** [comment]
에러가 발생한 구문이
> for tokens in self._tokenizer(raw_documents):
여기인가요?

funcition _tokenizer()의 코드를 수정하셔야 할 것 같은데요

twitter와 mecab는 서로 다른 태그를 사용하고 있어요

[형태소태그비교](https://docs.google.com/spreadsheets/d/1OGAjUvalBuX-oZvZ_-9tEfYD2gQe7hTGsgUpiiBSXI8/edit#gid=0)
