### ISSUE TITLE
NullPointerException when pos'ing blank sentence. / 빈 문자열을 pos 할 때 NullPointerExceptoin 발생.

### ISSUE THREAD

**Issue by daewonyoon** [konlpy/konlpy#206]
konlpy 버전 0.5.1, windows용 python 3.6 입니다.

- komoran.pos(' ') --> error
  - jpype._jexception.NullPointerExceptionPyRaisable: java.lang.NullPointerException
- kkma.pos(' ') --> error
  - jpype._jexception.NullPointerExceptionPyRaisable: java.lang.NullPointerException
- twitter.pos(' ') --> ok
  - []
- hannanum.pos(' ') --> hang
  - ...

```
Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import konlpy
>>> konlpy.__version__
'0.5.1'
>>> import konlpy.tag
>>> komoran = konlpy.tag.Komoran()
>>> komoran.pos(' ')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\PythonEnvs\textanal3664\lib\site-packages\konlpy\tag\_komoran.py", line 66, in pos
    result = self.jki.analyze(sentence).getTokenList()
jpype._jexception.NullPointerExceptionPyRaisable: java.lang.NullPointerException
>>> kkma = konlpy.tag.Kkma()
>>> kkma.pos(' ')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\PythonEnvs\textanal3664\lib\site-packages\konlpy\tag\_kkma.py", line 55, in pos
    sentences = self.jki.morphAnalyzer(phrase)
jpype._jexception.NullPointerExceptionPyRaisable: java.lang.NullPointerException
>>> tw = konlpy.tag.Twitter()
D:\PythonEnvs\textanal3664\lib\site-packages\konlpy\tag\_okt.py:16: UserWarning: "Twitter" has changed to "Okt" since KoNLPy v0.4.5.
  warn('"Twitter" has changed to "Okt" since KoNLPy v0.4.5.')
>>> tw.pos(' ')
[]
>>> import jpype
>>> jpype.__version__
'0.6.2'
```

**Comment by ken7005** [comment]
같은 문제인지는 모르겠으나, 0.4.4에서는 문제가 없던 코드가 0.5.1에서는 문제가 생깁니다.

from konlpy.tag import Komoran as Tagger

tagger = Tagger()
output = []
with open('wv_train_news_data.txt') as f:
        lines = f.readlines()
        taged_lines = []

        for line in lines:
                taged_lines.append(tagger.pos(line))

파일에서 읽은 line을 pos()에 넘겨주면, 위 코멘트와 동일하게, 마치 공백을 pos()에 넘겨준것 처럼_komoran.py 66라인에서 동일한 에러가 납니다. 

제 경우는 konlpy 0.4.4 버젼으로 바꾸고 돌리면 잘 돌아가구요.

**Comment by chlgudrbdn** [comment]
제 경우는 komoran을 썼는데 패키지 코드를 보니까 phrase.split('\n') 방식으로 나누는 부분이 있다는 것에 착안해서 미리 pos()함수에 대량의 텍스트를 넣게 전에 re.sub('\n+', "\n", text)같은 처리와 .split('\n')로 문장별로 나눈 뒤에
`for sentence in sentences:
    try:
         komoran.pos(sentence)
    exception Exception:
        print('error ', sentence)`
같은 식으로 처리해봤습니다. 일단 에러 나면 그냥 넘기는 식이라, 훗날 이에 대한 패키지 수준의 업데이트가 없지 않는 이상 이렇게 해야할 것 같습니다.
걸러진 문장들을 보면 이상하게 re.sub()를 이용한 전처리에도 걸러지지 않은 공백 문장들 같더군요.
