### ISSUE TITLE
runtime error 질문합니다.

### ISSUE THREAD

**Issue by dongkyunE** [konlpy/konlpy#216]
Traceback (most recent call last):
  File "exam.py", line 5, in <module>
    twitter = Twitter()
  File "C:\Users\ddd\Python36\lib\site-packages\konlpy\tag\_twitter.py", line 72, in __init__
    jvm.init_jvm(jvmpath)
  File "C:\Users\ddd\Python36\lib\site-packages\konlpy\jvm.py", line 51, in init_jvm
    '-ea', '-Xmx768m')
  File "C:\Users\ddd\Python36\lib\site-packages\jpype\_core.py", line 70, in startJVM
    _jpype.startup(jvm, tuple(args), True)
RuntimeError

이렇게 에러가 뜨는데 twitter 외에 어떤 클래스를 import해도 클래스 이름만 바뀌고 동일한 에러가 떠요.
해결방법이 있나요ㅠㅠ

**Comment by kensekense** [comment]
새로운 패키즈가 있어요
`"Twitter" has changed to "Okt" since KoNLPy v0.4.5.`
그래서 `from konlpy.tag import Okt` 그리고 `okt = Okt()` 해 봐요.
(저는 한국말을 배우고 있는데 잘 못 해요. 이게 틀리면 미안해요 ^^)

**Comment by gibiee** [comment]
윈도우의 경우 JPype1, 우분투의 경우 java 설치를 하세요.
공식문서 참고하세요.
http://konlpy.org/en/latest/install/#id2
