### ISSUE TITLE
OSError: Cannot access komoran-dic 에러에 관한 질문입니다

### ISSUE THREAD

**Issue by snaag** [konlpy/konlpy#221]
* 운영체제: macOS Mojave (Ver 10.14.2)
* Python: 3.6.7

안녕하세요! konlpy를 사용하려던 중 문제가 생겨 문의드립니다.
`pip3 install Jpype1` `pip3 install konlpy` 로 다운 받은 후,

`from konlpy.tag import Komoran` 를 한줄 입력하였는데

```
Traceback (most recent call last):
  File "/anaconda3/envs/hisTt/lib/python3.6/site-packages/konlpy/tag/_komoran.py", line 104, in __init__
    self.jki = komoranJavaPackage.Komoran(self.modelpath)
  File "/anaconda3/envs/hisTt/lib/python3.6/site-packages/jpype/_jpackage.py", line 62, in __call__
    raise TypeError("Package {0} is not Callable".format(self.__name))
TypeError: Package kr.co.shineware.nlp.komoran.core.Komoran is not Callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 5, in <module>
    komoran = Komoran()
  File "/anaconda3/envs/hisTt/lib/python3.6/site-packages/konlpy/tag/_komoran.py", line 106, in __init__
    raise IOError("Cannot access komoran-dic. Please leave an issue at https://github.com/konlpy/konlpy/issues")
OSError: Cannot access komoran-dic. Please leave an issue at https://github.com/konlpy/konlpy/issues
```

라는 에러가 발생하였습니다..
이슈를 보았지만 비슷한 상황을 발견하지 못하여 새로운 이슈를 남깁니다.

**Comment by snaag** [comment]
[#81](https://github.com/konlpy/konlpy/issues/81) 이슈를 참고하여 해결하였습니다!
[usryokousha](https://github.com/usryokousha) 님의 댓글
>저는 설치한 파일을 다시 보니 Anaconda3인 경우 JPype1-py3를 설치해야 된대요. 아마 오류가 발생하는 원인이 그런 거예요..


을 참고하여 `pip install JPype1-py3` 를 하였더니 해결되었습니다!
