### ISSUE TITLE
self.jki.analyze(sentence).getTokenList() when reading from file using Komoran

### ISSUE THREAD

**Issue by patrickdrouin** [konlpy/konlpy#250]
Hello,

Thank you for making konlpy available to us.

I am having a strange issue when using Komoran to tag strings coming from a file. It works fine when I pass the string directly. I tried the same code using Kkma and I do not get the same error. I have no clue what could be causing this. Here's the code : 

from konlpy.tag import Komoran
tagger = Komoran()

f = open('15.txt', 'r')
print('1970년대 2차에 걸쳐 발생한 석유파동 이후 많은 선진국들은 신재생에너지 기술개발과 보급에 관심을 갖기 시작하였다.')
print(tagger.pos('1970년대 2차에 걸쳐 발생한 석유파동 이후 많은 선진국들은 신재생에너지 기술개발과 보급에 관심을 갖기 시작하였다.'))
print('\n')
for line in f:
	print(line)
	print(tagger.pos(line))

Here's the output
$ python3 try_komoran.py 
1970년대 2차에 걸쳐 발생한 석유파동 이후 많은 선진국들은 신재생에너지 기술개발과 보급에 관심을 갖기 시작하였다.
[('1970년대', 'NNP'), ('2', 'SN'), ('차', 'NNB'), ('에', 'JKB'), ('걸치', 'VV'), ('어', 'EC'), ('발생', 'NNG'), ('하', 'XSV'), ('ㄴ', 'ETM'), ('석유', 'NNP'), ('파동', 'NNP'), ('이후', 'NNG'), ('많', 'VA'), ('은', 'ETM'), ('선진국', 'NNG'), ('들', 'XSN'), ('은', 'JX'), ('신', 'XPN'), ('재생', 'NNP'), ('에너지', 'NNP'), ('기술', 'NNG'), ('개발', 'NNG'), ('과', 'JC'), ('보급', 'NNG'), ('에', 'JKB'), ('관심', 'NNG'), ('을', 'JKO'), ('갖', 'VV'), ('기', 'ETN'), ('시작', 'NNG'), ('하', 'XSV'), ('았', 'EP'), ('다', 'EF'), ('.', 'SF')]

1970년대 2차에 걸쳐 발생한 석유파동 이후 많은 선진국들은 신재생에너지 기술개발과 보급에 관심을 갖기 시작하였다. 

Traceback (most recent call last):
  File "try_komoran.py", line 12, in <module>
    print(tagger.pos(line))
  File "/home/drouinp/.local/lib/python3.5/site-packages/konlpy/tag/_komoran.py", line 66, in pos
    result = self.jki.analyze(sentence).getTokenList()
jpype._jexception.NullPointerExceptionPyRaisable: java.lang.NullPointerException

As far as I can see the string read from the file is the same as the one passed in the first case (it's a copy and paste from the file). I tried catching the error to bypass the problematic sentences but I get the exact same error on every line read from the file. 

The file is Unicode with BOM : 
$ file 15.txt
15.txt: UTF-8 Unicode (with BOM) text, with CRLF, LF line terminators

Could the BOM be causing this to Komoran only? 

Thanks,
Patrick

**Comment by patrickdrouin** [comment]
Just so that you see it works with Kkma using the same file. 

**Code:**
from konlpy.tag import Kkma
tagger = Kkma()

f = open('15.txt', 'r')
print('1970년대 2차에 걸쳐 발생한 석유파동 이후 많은 선진국들은 신재생에너지 기술개발과 보급에 관심을 갖기 시작하였다.')
print(tagger.pos('1970년대 2차에 걸쳐 발생한 석유파동 이후 많은 선진국들은 신재생에너지 기술개발과 보급에 관심을 갖기 시작하였다.'))
print('\n')
for line in f:
	print(line)
	print(tagger.pos(line))

**Output:** 
$python3 try_komoran.py 
1970년대 2차에 걸쳐 발생한 석유파동 이후 많은 선진국들은 신재생에너지 기술개발과 보급에 관심을 갖기 시작하였다.
[('1970', 'NR'), ('년대', 'NNM'), ('2', 'NR'), ('차', 'NNM'), ('에', 'JKM'), ('걸치', 'VV'), ('어', 'ECS'), ('발생', 'NNG'), ('하', 'XSV'), ('ㄴ', 'ETD'), ('석유', 'NNG'), ('파동', 'NNP'), ('이후', 'NNG'), ('많', 'VA'), ('은', 'ETD'), ('선진국', 'NNG'), ('들', 'XSN'), ('은', 'JX'), ('신', 'XPN'), ('재생', 'NNG'), ('에너지', 'NNG'), ('기술', 'NNG'), ('개발', 'NNG'), ('과', 'JKM'), ('보급', 'NNG'), ('에', 'JKM'), ('관심', 'NNG'), ('을', 'JKO'), ('갖', 'VV'), ('기', 'ETN'), ('시작', 'NNG'), ('하', 'XSV'), ('였', 'EPT'), ('다', 'EFN'), ('.', 'SF')]


1970년대 2차에 걸쳐 발생한 석유파동 이후 많은 선진국들은 신재생에너지 기술개발과 보급에 관심을 갖기 시작하였다. 

[('\ufeff', 'SW'), ('1970', 'NR'), ('년대', 'NNM'), ('2', 'NR'), ('차', 'NNM'), ('에', 'JKM'), ('걸치', 'VV'), ('어', 'ECS'), ('발생', 'NNG'), ('하', 'XSV'), ('ㄴ', 'ETD'), ('석유', 'NNG'), ('파동', 'NNP'), ('이후', 'NNG'), ('많', 'VA'), ('은', 'ETD'), ('선진국', 'NNG'), ('들', 'XSN'), ('은', 'JX'), ('신', 'XPN'), ('재생', 'NNG'), ('에너지', 'NNG'), ('기술', 'NNG'), ('개발', 'NNG'), ('과', 'JKM'), ('보급', 'NNG'), ('에', 'JKM'), ('관심', 'NNG'), ('을', 'JKO'), ('갖', 'VV'), ('기', 'ETN'), ('시작', 'NNG'), ('하', 'XSV'), ('였', 'EPT'), ('다', 'EFN'), ('.', 'SF')]

**Comment by minhoryang** [comment]
I tried to reproduce with BOM input:
<img width="400" alt="스크린샷 2019-10-31 오후 11 30 20" src="https://user-images.githubusercontent.com/1270855/67955799-74d41380-fc36-11e9-964f-73e54acf6792.png">

But it works well.

Maybe newline(`\r\n`) could be a problem:
<img width="700" alt="스크린샷 2019-10-31 오후 11 30 29" src="https://user-images.githubusercontent.com/1270855/67955798-74d41380-fc36-11e9-8e57-3a0cdebef90b.png">

FYI, reading BOM file like this:
<img width="380" alt="스크린샷 2019-10-31 오후 11 33 57" src="https://user-images.githubusercontent.com/1270855/67956240-178c9200-fc37-11e9-9d7e-5a95b4307232.png">
