### ISSUE TITLE
Documentation을 생성하는데 문제가 있습니다.

### ISSUE THREAD

**Issue by minhoryang** [konlpy/konlpy#272]
```bash
$ make show_docs
or
$ cd docs && make html
or
$ cd docs && sphinx-build -v -b html -d _build/doctrees . _build/html
```

```pytb
Sphinx 버전 2.2.1 실행 중

Traceback (most recent call last):
  File "/Users/minhoryang/.anyenv/envs/pyenv/versions/3.7.4-konlpy/lib/python3.7/site-packages/sphinx/cmd/build.py", line 275, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/Users/minhoryang/.anyenv/envs/pyenv/versions/3.7.4-konlpy/lib/python3.7/site-packages/sphinx/application.py", line 260, in __init__
    self.events.emit('config-inited', self.config)
  File "/Users/minhoryang/.anyenv/envs/pyenv/versions/3.7.4-konlpy/lib/python3.7/site-packages/sphinx/events.py", line 103, in emit
    results.append(callback(self.app, *args))
  File "/Users/minhoryang/.anyenv/envs/pyenv/versions/3.7.4-konlpy/lib/python3.7/site-packages/sphinx/config.py", line 483, in check_confval_types
    default=type(default)))
ValueError: Single '}' encountered in format string

Exception occurred:
  File "/Users/minhoryang/.anyenv/envs/pyenv/versions/3.7.4-konlpy/lib/python3.7/site-packages/sphinx/config.py", line 483, in check_confval_types
    default=type(default)))
ValueError: Single '}' encountered in format string
The full traceback has been saved in /var/folders/2z/s0qpljwj7hd60f2pm1s2f7mw0000gn/T/sphinx-err-ojgf1bw1.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

문제가 발생하는 지점이 logging하는 부분으로 보아 sphinx 자체의 문제로 보이고, 실행 시 `LANG=C`를 앞에 붙여 실행하면 문제 없이 잘 진행됩니다.

해당하는 로깅 문구는 `설정 값 `{name}'은(는) `{{current .__name__}' 유형이며, 기본값은 `{default.__name__}'입니다.`로 sphinx 의 i18n 문제로 보입니다.

**Comment by minhoryang** [comment]
Blocking #271

**Comment by minhoryang** [comment]
https://github.com/sphinx-doc/sphinx/blob/34acdc3/sphinx/locale/ko/LC_MESSAGES/sphinx.po#L239

**Comment by minhoryang** [comment]
Blocked https://github.com/sphinx-doc/sphinx/issues/6815

**Comment by minhoryang** [comment]
Not blocked - 무시하고 배포할 수 있게 되었습니다.
