### ISSUE TITLE
업데이트 후 JPype1 문제가 생겼습니다

### ISSUE THREAD

**Issue by HelgaKr** [konlpy/konlpy#287]
안녕하세요!

저는 업데이트 후 이런 문제가 생겼습니다:
Traceback (most recent call last):
  File "C:/Users/Helga/.PyCharm2018.3/config/scratches/mainapp.py", line 82, in <module>
    filter(f)
  File "C:/Users/Helga/.PyCharm2018.3/config/scratches/mainapp.py", line 43, in filter
    nouns = okt.nouns(data)
  File "C:\Users\Helga\PycharmProjects\Topik\untitled6\lib\site-packages\konlpy\tag\_okt.py", line 72, in nouns
    tagged = self.pos(phrase)
  File "C:\Users\Helga\PycharmProjects\Topik\untitled6\lib\site-packages\konlpy\tag\_okt.py", line 63, in pos
    jpype.java.lang.Boolean(stem)).toArray()
TypeError: No matching overloads found for kr.lucypark.okt.OktInterface.tokenize(list,java.lang.Boolean,java.lang.Boolean), options are:
	public java.util.List kr.lucypark.okt.OktInterface.tokenize(java.lang.String,java.lang.Boolean,java.lang.Boolean)

	at JPMethod::findOverload(native\common\jp_method.cpp:242)
	at JPMethod::findOverload(native\common\jp_method.cpp:245)
	at JPMethod::invoke(native\common\jp_method.cpp:253)
	at PyJPMethod::__call__(native\python\pyjp_method.cpp:142)
`

konlpy 0.5.1도 설치해 봤어요. 안 도왔어요. 

저는 Win 64가 있고 Python 3.7 사용하고 있어요. (PyCharm) 

이 문제를 해결하는 방법을 알려 주시면 정말 고마울 가예요. 
감사합니다!

**Comment by minhoryang** [comment]
```python
nouns = okt.nouns(data)
```
이런 코드를 작성하신 것 같습니다.
현재 문제가 발생하는 이유는 data의 타입이 리스트라서 발생하는 것입니다.

```python
nouns = []
for line in data:
    nouns.extend(okt.nouns(line))
```

**Comment by minhoryang** [comment]
@HelgaKr ping
