### ISSUE TITLE
Okt API 사용 시 에러 AttributeError: 'java.lang.String' object has no attribute 'rsplit'

### ISSUE THREAD

**Issue by oyj940331** [konlpy/konlpy#331]
안녕하세요 간단하게 Okt API 테스트를 해보려고 하는데 다음과 같은 에러가 발생합니다.
현재 ubuntu 18.04 에서 진행하고 있고 python 3.6.9 / konlpy 0.5.1 / openjdk version "1.8.0_265" 버전 사용 중입니다.

>>> from konlpy.tag import Okt
>>> okt = Okt()
>>> print(okt.morphs(u'단독입찰보다 복수입찰의 경우'))

python 인터프리터에서 입력한 코드 입니다. 아래는 에러 내용입니다.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/konlpy/tag/_okt.py", line 78, in morphs
    return [s for s, t in self.pos(phrase, norm=norm, stem=stem)]
  File "/usr/local/lib/python3.6/dist-packages/konlpy/tag/_okt.py", line 67, in pos
    return [tuple(t.rsplit('/', 1)) for t in tokens]
  File "/usr/local/lib/python3.6/dist-packages/konlpy/tag/_okt.py", line 67, in <listcomp>
    return [tuple(t.rsplit('/', 1)) for t in tokens]
AttributeError: 'java.lang.String' object has no attribute 'rsplit'

이 에러가 발생하는 이유를 알 수 있을까요? 에러 메세지를 검색해도 아무런 정보를 얻을 수가 없었습니다....

**Comment by oyj940331** [comment]
jpype1 1.0.1 버전이 기본으로 설치되어있는데 0.6.3 으로 설치하니 해결되었네요
