### ISSUE TITLE
konlpy를 사용하는데 오류가 뜹니다. <Java package kr.lucypark.okt.OktInterface._name> is not Callable

### ISSUE THREAD

**Issue by good2a1227** [konlpy/konlpy#332]
코엔엘로 네이버 기사를 자연어 분석을 하고자 자연어 분석을 배우려고 하는데 Konlpy가 제대로 실행이 되지를 않네요...

다음과 같은 코드를 입력해더니
from konlpy.tag import Okt
okt = Okt()

파이참에서 다음과 같은 오류가 뜨네요.
Traceback (most recent call last):
  File "C:/Users/user/Desktop/기사_자연어_분석/main.py", line 228, in <module>
    okt = Okt()
  File "C:\Users\user\Desktop\기사_자연어_분석\venv\lib\site-packages\konlpy\tag\_okt.py", line 95, in __init__
    self.jki = OktInterfaceJavaClass()
  File "C:\Users\user\Desktop\기사_자연어_분석\venv\lib\site-packages\jpype\_jpackage.py", line 124, in __call__
    raise TypeError("Package {0} is not Callable".format(self._name))
TypeError: Package <Java package kr.lucypark.okt.OktInterface._name> is not Callable

임포트 하는데 까지는 오류가 없는데 객체를 선언하니 오류가 생기네요.
문제가 뭘까요... 며칠째 해결하지 못하고 있습니다.

해본 것들:
환경변수 JAVA_HOME의 위치를 시스템 변수로 옮겨보기
PATH에서 %JAVA_HOME%\bin을 적어보기
자바 최신버전으로 다시 설치하기
파이썬 자바 컴퓨터 모두 64비트인지 확인하기
재부팅 등등..

인터넷에 있는 웬만한건 다 해본거 같은데 영 모르겠네요.
애초에 저랑 같은 오류코드를 본 사람을 못찾았습니다...ㅜㅜ

저좀 도와주세요..

konlpy 버전 : 0.5.2
python 버전 : 3.8

**Comment by hexists** [comment]
@good2a1227 

안녕하세요~
지나가다가 혹시 이 문제를 해결할 수는 없을까 궁금해서 몇가지 확인해 본 내용 공유드립니다.
아쉽게도 문제를 재현하지 못해서 정확한 해결 방법이 될지는 모르겠네요.

```
okt = Okt()
```
위 호출 시점에 실행되는 코드를 확인해보니, [__init__.py](https://github.com/konlpy/konlpy/blob/master/konlpy/__init__.py#L11) 가 실행되고,
**from konlpy.jvm import init_jvm** 이 실행됩니다.

init_jvm이 실행되면서 **Okt()** 인스턴스를 만듭니다.

이 과정에서 java로 개발된 형태소 분석기의 class를 python에서 사용할 수 있도록 불러옵니다.

이 때 필요한 변수로 jvmpath, classpath가 있는데요.

추측하기로는 이 두 변수가 제대로 설정되었는지 확인이 필요할 것 같습니다.
https://github.com/konlpy/konlpy/blob/master/konlpy/jvm.py#L53-L55
여기 있는 classpath와 jvmpath가 제대로 설정되었는지, 필요한 path가 모두 있는지를 확인하셔야 할 것 같습니다.

제가 개발하는 환경에서는 재현이 안되서 가능한 선에서 답변 드리는 점 양해 부탁드립니다.

감사합니다.
