### ISSUE TITLE
[macOs BigSur 11.2.3] Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by de-elebit** [konlpy/konlpy#348]
이슈들을 봤을때 자바 버전에 관한 이슈들이 많은거 같은데 하위 버전이 아닌 상위버전임에도 해당 오류가 발생해 이슈 남깁니다

Traceback (most recent call last):
  File "/Users/taek2/Projects/python/chatbotPrac/libPrac.py", line 3, in <module>
    kkma = Kkma()
  File "/Users/taek2/anaconda3/envs/ML/lib/python3.7/site-packages/konlpy/tag/_kkma.py", line 95, in __init__
    jvm.init_jvm(jvmpath, max_heap_size)
  File "/Users/taek2/anaconda3/envs/ML/lib/python3.7/site-packages/konlpy/jvm.py", line 67, in init_jvm
    convertStrings=True)
  File "/Users/taek2/anaconda3/envs/ML/lib/python3.7/site-packages/jpype/_core.py", line 222, in startJVM
    ignoreUnrecognized, convertStrings, interrupt)
SystemError: java.lang.UnsupportedClassVersionError: org/jpype/classloader/DynamicClassLoader : Unsupported major.minor version 52.0

사용 환경 
Python 3.7
Java 1.8.0_281
macOs BigSur 11.2.3

**Comment by combacsa** [comment]
안녕하세요, @Elebbit 님. 터미널에서 `java -version` 을 실행 시 표시되는 Java version 확인 부탁드립니다. 오류 메시지 내용으로는 JDK 8 과 하위 버전의 java runtime 이 함께 설치되어 있는 상태이신 것이 아닌지 의심됩니다. 또, 현재 최신 버전의 konlpy ( `0.6.0` )에서 여전히 같은 이슈가 있는지도 확인 부탁드립니다. `$JAVA_HOME` 환경 변수도 바르게 설정되어 있는지요?
