### ISSUE TITLE
InvalidPathException

### ISSUE THREAD

**Issue by carnoxen** [konlpy/konlpy#349]
```
PS C:\WINDOWS\system32> python
Python 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from konlpy.tag import *
>>> tagger = Okt()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ddd\AppData\Local\Programs\Python\Python39\lib\site-packages\konlpy\tag\_okt.py", line 91, in __init__
    jvm.init_jvm(jvmpath, max_heap_size)
  File "C:\Users\ddd\AppData\Local\Programs\Python\Python39\lib\site-packages\konlpy\jvm.py", line 64, in init_jvm
    jpype.startJVM(jvmpath, '-Djava.class.path=%s' % classpath,
  File "C:\Users\ddd\AppData\Local\Programs\Python\Python39\lib\site-packages\jpype\_core.py", line 221, in startJVM
    _jpype.startup(jvmpath, tuple(args),
SystemError: java.nio.file.InvalidPathException: Illegal char <*> at index 82: C:\Users\ddd\AppData\Local\Programs\Python\Python39\Lib\site-packages\konlpy\java\*
>>> tagger = Okt()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ddd\AppData\Local\Programs\Python\Python39\lib\site-packages\konlpy\tag\_okt.py", line 91, in __init__
    jvm.init_jvm(jvmpath, max_heap_size)
  File "C:\Users\ddd\AppData\Local\Programs\Python\Python39\lib\site-packages\konlpy\jvm.py", line 64, in init_jvm
    jpype.startJVM(jvmpath, '-Djava.class.path=%s' % classpath,
  File "C:\Users\ddd\AppData\Local\Programs\Python\Python39\lib\site-packages\jpype\_core.py", line 221, in startJVM
    _jpype.startup(jvmpath, tuple(args),
SystemError: java.lang.UnsatisfiedLinkError: Native Library C:\Users\ddd\AppData\Local\Programs\Python\Python39\Lib\site-packages\_jpype.cp39-win_amd64.pyd already loaded in another classloader
>>> tagger = Okt()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ddd\AppData\Local\Programs\Python\Python39\lib\site-packages\konlpy\tag\_okt.py", line 91, in __init__
    jvm.init_jvm(jvmpath, max_heap_size)
  File "C:\Users\ddd\AppData\Local\Programs\Python\Python39\lib\site-packages\konlpy\jvm.py", line 64, in init_jvm
    jpype.startJVM(jvmpath, '-Djava.class.path=%s' % classpath,
  File "C:\Users\ddd\AppData\Local\Programs\Python\Python39\lib\site-packages\jpype\_core.py", line 221, in startJVM
    _jpype.startup(jvmpath, tuple(args),
SystemError: java.lang.UnsatisfiedLinkError: Native Library C:\Users\ddd\AppData\Local\Programs\Python\Python39\Lib\site-packages\_jpype.cp39-win_amd64.pyd already loaded in another classloader
>>> tagger = Okt()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ddd\AppData\Local\Programs\Python\Python39\lib\site-packages\konlpy\tag\_okt.py", line 91, in __init__
    jvm.init_jvm(jvmpath, max_heap_size)
  File "C:\Users\ddd\AppData\Local\Programs\Python\Python39\lib\site-packages\konlpy\jvm.py", line 64, in init_jvm
    jpype.startJVM(jvmpath, '-Djava.class.path=%s' % classpath,
  File "C:\Users\ddd\AppData\Local\Programs\Python\Python39\lib\site-packages\jpype\_core.py", line 221, in startJVM
    _jpype.startup(jvmpath, tuple(args),
AttributeError: module 'importlib.util' has no attribute 'find_spec'
>>> tagger = Okt()
PS C:\WINDOWS\system32>
```

무엇 때문에 나는 에러인지 모르겠습니다. 파이썬, 자바, 윈도우 모두 최신인데... 사양은 이렇습니다.
python 3.9.2
java 16
windows 20h2 64bit

JPype1까지 최신으로 다 깔아놨습니다.

**Comment by 6unpk** [comment]
저도 해당 증상 똑같이 겪고있는데 디버깅해서 konly\jvm.py에서 다음과 같이(주석친 부분) 와일드카드 경로 패턴 리스트 부분을 지우고 테스트 해보니 일단은 해결이 되더라고요. 이전엔 이런 문제가 없었던 것 같은데 왜그런지는 정확히 잘 모르겠네요;;

```
folder_suffix = [
        # JAR
        '{0}',
        # Java sources
        '{0}{1}bin',
        '{0}{1}*', # <- 문제가 되는 부분1
        # Hannanum
        '{0}{1}jhannanum-0.8.4.jar',
        # Kkma
        '{0}{1}kkma-2.0.jar',
        # Komoran3
        '{0}{1}aho-corasick.jar',
        '{0}{1}shineware-common-1.0.jar',
        '{0}{1}shineware-ds-1.0.jar',
        '{0}{1}komoran-3.0.jar',
        # Twitter (Okt)
        '{0}{1}snakeyaml-1.12.jar',
        '{0}{1}scala-library-2.12.3.jar',
        '{0}{1}open-korean-text-2.1.0.jar',
        '{0}{1}twitter-text-1.14.7.jar',
        '{0}{1}*' # <- 문제가 되는 부분 2
    ]
```

**Comment by taherromdhane** [comment]
Like @6unpk said, the problem is in this file; 'konly\jvm.py'. When I deleted the stars in the paths, it worked for me.
```
folder_suffix = [
        # JAR
        '{0}',
        # Java sources
        '{0}{1}bin',
        '{0}{1}*', # <- Delete the '*' here
        # Hannanum
        '{0}{1}jhannanum-0.8.4.jar',
        # Kkma
        '{0}{1}kkma-2.0.jar',
        # Komoran3
        '{0}{1}aho-corasick.jar',
        '{0}{1}shineware-common-1.0.jar',
        '{0}{1}shineware-ds-1.0.jar',
        '{0}{1}komoran-3.0.jar',
        # Twitter (Okt)
        '{0}{1}snakeyaml-1.12.jar',
        '{0}{1}scala-library-2.12.3.jar',
        '{0}{1}open-korean-text-2.1.0.jar',
        '{0}{1}twitter-text-1.14.7.jar',
        '{0}{1}*' # <- Delete the '*' here
    ]
```

**Comment by carnoxen** [comment]
https://github.com/konlpy/konlpy/pull/370
