### ISSUE TITLE
ImportError DLL

### ISSUE THREAD

**Issue by seiferkiller0421** [konlpy/konlpy#352]
When running the basic code:
`from konlpy.tag import Okt`

I am getting this error:
Traceback (most recent call last):
  File "C:\Users\Jovin\Desktop\Korgee\04 Python\konlpy_script.py", line 1, in <module>
    from konlpy.tag import Okt
  File "C:\Users\Jovin\AppData\Local\Programs\Python\Python39\lib\site-packages\konlpy\__init__.py", line 12, in <module>
    from konlpy import (
  File "C:\Users\Jovin\AppData\Local\Programs\Python\Python39\lib\site-packages\konlpy\tag\__init__.py", line 6, in <module>
    from konlpy.tag._hannanum import Hannanum
  File "C:\Users\Jovin\AppData\Local\Programs\Python\Python39\lib\site-packages\konlpy\tag\_hannanum.py", line 7, in <module>
    import jpype
  File "C:\Users\Jovin\AppData\Local\Programs\Python\Python39\lib\site-packages\jpype\__init__.py", line 18, in <module>
    import _jpype
ImportError: DLL load failed while importing _jpype: A dynamic link library (DLL) initialization routine failed.

**Comment by combacsa** [comment]
Hello @seiferkiller0421, could you please check if recent release (on Jan.02 this year) could solve the problem you had before? I'm looking for the specific `JPype1` version you might have used but it's not so easy for me to find one. Thanks in advance.
