### ISSUE TITLE
M1 Mac에서의 JVM/JDK 문제

### ISSUE THREAD

**Issue by c-juhwan** [konlpy/konlpy#353]
M1 칩이 탑재된 맥에서 java 환경변수가 설정되어 있지 않거나, JDK가 설치되어 있고 환경변수가 설정되어 있더라도 JDK에 따라 konlpy를 사용할 때 다음과 같은 오류가 발생합니다.

```python
# Test code 
from konlpy.tag import Okt
okt = Okt()
text = "아 나는 역시 밤에 일이 잘된다."

print(okt.morphs(text, stem=True))
```

```
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    okt = Okt()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/NLP-tf/lib/python3.8/site-packages/konlpy/tag/_okt.py", line 91, in __init__
    jvm.init_jvm(jvmpath, max_heap_size)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/NLP-tf/lib/python3.8/site-packages/konlpy/jvm.py", line 64, in init_jvm
    jpype.startJVM(jvmpath, '-Djava.class.path=%s' % classpath,
  File "/opt/homebrew/Caskroom/miniforge/base/envs/NLP-tf/lib/python3.8/site-packages/jpype/_core.py", line 221, in startJVM
    _jpype.startup(jvmpath, tuple(args),
OSError: [Errno 0] JVM DLL not found: /Library/Java/JavaVirtualMachines/jdk-15.0.2.jdk/Contents/Home/lib/libjli.dylib
```

Oracle JDK나 AdoptOpenJDK는 환경변수를 설정하더라도 마찬가지 오류가 발생합니다. 아마 x86용으로만 있어서 그런 것 같아요.

제가 찾은 작동 가능한 JDK는
https://www.azul.com/downloads/zulu-community/?version=java-15-mts&os=macos&architecture=arm-64-bit&package=jdk
이 Zulu Open JDK의 arm64용 15버전입니다. 16버전은 또 작동이 안 되네요.

위 JDK를 설치하고 

```
% open ./.zshrc
```

./zshrc 내에 아래를 작성 후 저장하고
```
# JAVA PATH
export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-15.jdk/Contents/Home
export PATH=${PATH}:$JAVA_HOME/bin:
```

```
% source ./.zshrc
```

다시 코드를 실행해보면 

```
[0.002s][warning][os,thread] Attempt to protect stack guard pages failed (0x000000016d4b0000-0x000000016d4bc000).
[0.002s][warning][os,thread] Attempt to deallocate stack guard pages failed.
['아', '나', '는', '역시', '밤', '에', '일이', '잘', '되다', '.']
```
warning이 뜨긴 하는데, 테스트 코드 뿐만 아니라 실제 사용해본 결과 현재까지 확인한 바로는 문제 없이 잘 동작하는 것 같습니다.

이슈를 작성해 보는 것이 처음이라 적절하게 썼는지 잘 모르겠네요... 죄송합니다. 
이건 사실 konlpy 패키지의 문제라기보다는 M1 칩의 자바 의존성 문제인 것 같긴 합니다만...
그래도 누군가에게 도움이 됐으면 좋겠네요. 감사합니다.

**Comment by petershin89** [comment]
감사합니다. julu 자바 이용하니 잘 됐습니다. 감사합니다.

**Comment by rurara** [comment]
감사합니다 새로운 장난감 쓰고 싶다고 m1으로 사서 삽질하고 있는데 덕분에 해결되었습니다

**Comment by tjdrhkd141** [comment]
안녕하세요? 저도 완전히 동일한 에러메세지가 나타나서 링크 달아주신 곳에 들어가 jdk 를 다운받았습니다(현재 /Users/컴이름/ <-에 저장해둔 상태입니다. 그런데 터미널에서 open ./.zshrc를 입력 후 새로 뜨는 창에 수정하려고 하니 사용자가 .zshrc파일을 소유하고 있지 않으며 이에 대한 쓰기 권한이 없다고 나옵니다.. 이럴땐 어떻게 해야 할까요?
또한 export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-15.jdk/Contents/Home
export PATH=${PATH}:$JAVA_HOME/bin: 이 내용을 .zshrc 안에 어디에 적어야 할까요? 맨 아래에 적으면 될까요?
완전 코린이입니다. 답변 기다리겠습니다 ㅠㅠ

**Comment by hexists** [comment]
@tjdrhkd141 
안녕하세요~

먼저 아래와 같은 메세지가 나오는 이유를 추측해 볼 때,
```
사용자가 .zshrc파일을 소유하고 있지 않으며 이에 대한 쓰기 권한이 없다고 나옵니다.
```

1) .zshrc 경로가 잘못된 경우
open ~/.zshrc 를 실행해보시고, 동일한 오류가 나오는지 확인해보시면 될 것 같아요.

2) 파일 경로는 맞으나 맥에서 파일 접근 권한이 없는 경우
https://support.apple.com/ko-kr/guide/mac-help/mchlp1203/mac
위 페이지를 참고해서 권한 설정을 해보시면 될 것 같아요.

etc) export 내용은 파일 맨 아래 적으면 될 것 같아요. 위치는 크게 상관없으나 다른 환경변수 설정보다 나중에 적는 것이 좋을 것 같습니다.

해결 방법을 찾으셨으면 좋겠네요😄

**Comment by c-juhwan** [comment]
> 안녕하세요? 저도 완전히 동일한 에러메세지가 나타나서 링크 달아주신 곳에 들어가 jdk 를 다운받았습니다(현재 /Users/컴이름/ <-에 저장해둔 상태입니다. 그런데 터미널에서 open ./.zshrc를 입력 후 새로 뜨는 창에 수정하려고 하니 사용자가 .zshrc파일을 소유하고 있지 않으며 이에 대한 쓰기 권한이 없다고 나옵니다.. 이럴땐 어떻게 해야 할까요?
> 또한 export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-15.jdk/Contents/Home
> export PATH=${PATH}:$JAVA_HOME/bin: 이 내용을 .zshrc 안에 어디에 적어야 할까요? 맨 아래에 적으면 될까요?
> 완전 코린이입니다. 답변 기다리겠습니다 ㅠㅠ

@tjdrhkd141 
안녕하세요. 위의 @hexists 님께서 말씀해주신대로 export 내용은 어디에 적든 상관 없으나 보통 맨 뒷부분에 넣는게 가장 무난하지 않나 싶습니다.
덧붙여, 권한이 없어서 .zshrc 파일이 열리지 않는 경우에는 sudo 명령어를 붙여서 열어보시는 것이 어떨까 싶습니다. 좋은 하루 되세요!

**Comment by tjdrhkd141** [comment]
> 1. .zshrc 경로가 잘못된 경우
>    open ~/.zshrc 를 실행해보시고, 동일한 오류가 나오는지 확인해보시면 될 것 같아요.
> 2. 파일 경로는 맞으나 맥에서 파일 접근 권한이 없는 경우
>    https://support.apple.com/ko-kr/guide/mac-help/mchlp1203/mac
>    위 페이지를 참고해서 권한 설정을 해보시면 될 것 같아요.
> 

친절한 답변 너무 감사드립니다 !!
그렇지만 open ~/.zshrc 로 실행해도 동일한 오류가 나타나고, 아래 글쓴이 분의 말씀대로 sudo open ~/.zshrc로 열어도 
동일하게 접근 권한이 없다고 나옵니다 ㅠㅠ

그래서 링크 달아주신 것 참고하고 .zshrc 파일을 찾아서 자물쇠를 풀어보려했으니 .zshrc 파일이 어디있는지 도저히 찾을 수가 없습니다 ㅠㅠ

**Comment by tjdrhkd141** [comment]
> @tjdrhkd141
> 안녕하세요. 위의 @hexists 님께서 말씀해주신대로 export 내용은 어디에 적든 상관 없으나 보통 맨 뒷부분에 넣는게 가장 무난하지 않나 싶습니다.
> 덧붙여, 권한이 없어서 .zshrc 파일이 열리지 않는 경우에는 sudo 명령어를 붙여서 열어보시는 것이 어떨까 싶습니다. 좋은 하루 되세요!


친절한 답변 너무 감사드립니다 !!
그렇지만 말씀해주신 대로 sudo open ~/.zshrc로 열어도 동일하게 접근 권한이 없다고 나옵니다 ㅠㅠ

제 생각에는 파일의 위치를 찾아서 위에 링크 달아주신 것처럼 자물쇠를 풀어 읽기 권한을 쓰기권한까지 가능하게 바꾸면 
문제가 해결될 것 같은데 .zshrc 파일이 어디에 있는지 도저히 찾을수가 없습니다.ㅠㅠ

**Comment by tjdrhkd141** [comment]
> @tjdrhkd141
> 안녕하세요~
> 
> 먼저 아래와 같은 메세지가 나오는 이유를 추측해 볼 때,
> 
> ```
> 사용자가 .zshrc파일을 소유하고 있지 않으며 이에 대한 쓰기 권한이 없다고 나옵니다.
> ```
> 
> 1. .zshrc 경로가 잘못된 경우
>    open ~/.zshrc 를 실행해보시고, 동일한 오류가 나오는지 확인해보시면 될 것 같아요.
> 2. 파일 경로는 맞으나 맥에서 파일 접근 권한이 없는 경우
>    https://support.apple.com/ko-kr/guide/mac-help/mchlp1203/mac
>    위 페이지를 참고해서 권한 설정을 해보시면 될 것 같아요.
> 
> etc) export 내용은 파일 맨 아래 적으면 될 것 같아요. 위치는 크게 상관없으나 다른 환경변수 설정보다 나중에 적는 것이 좋을 것 같습니다.
> 
> 해결 방법을 찾으셨으면 좋겠네요😄

open ./.zshrc 도 안됐고, sudo를 붙여도 안되어서
vi로 여니까 편집이 됐습니다 !!
julu 자바가 아니어도 konlpy가 잘 돌아가네요 ! 
감사합니다 ^^

**Comment by tjdrhkd141** [comment]
> > 안녕하세요? 저도 완전히 동일한 에러메세지가 나타나서 링크 달아주신 곳에 들어가 jdk 를 다운받았습니다(현재 /Users/컴이름/ <-에 저장해둔 상태입니다. 그런데 터미널에서 open ./.zshrc를 입력 후 새로 뜨는 창에 수정하려고 하니 사용자가 .zshrc파일을 소유하고 있지 않으며 이에 대한 쓰기 권한이 없다고 나옵니다.. 이럴땐 어떻게 해야 할까요?
> > 또한 export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-15.jdk/Contents/Home
> > export PATH=${PATH}:$JAVA_HOME/bin: 이 내용을 .zshrc 안에 어디에 적어야 할까요? 맨 아래에 적으면 될까요?
> > 완전 코린이입니다. 답변 기다리겠습니다 ㅠㅠ
> 
> @tjdrhkd141
> 안녕하세요. 위의 @hexists 님께서 말씀해주신대로 export 내용은 어디에 적든 상관 없으나 보통 맨 뒷부분에 넣는게 가장 무난하지 않나 싶습니다.
> 덧붙여, 권한이 없어서 .zshrc 파일이 열리지 않는 경우에는 sudo 명령어를 붙여서 열어보시는 것이 어떨까 싶습니다. 좋은 하루 되세요!

open ./.zshrc 도 안됐고, sudo를 붙여도 안되어서
vi로 여니까 편집이 됐습니다 !!
julu 자바가 아니어도 konlpy가 잘 돌아가네요 ! 
감사합니다 ^^

**Comment by tjdrhkd141** [comment]
> > > 안녕하세요? 저도 완전히 동일한 에러메세지가 나타나서 링크 달아주신 곳에 들어가 jdk 를 다운받았습니다(현재 /Users/컴이름/ <-에 저장해둔 상태입니다. 그런데 터미널에서 open ./.zshrc를 입력 후 새로 뜨는 창에 수정하려고 하니 사용자가 .zshrc파일을 소유하고 있지 않으며 이에 대한 쓰기 권한이 없다고 나옵니다.. 이럴땐 어떻게 해야 할까요?
> > > 또한 export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-15.jdk/Contents/Home
> > > export PATH=${PATH}:$JAVA_HOME/bin: 이 내용을 .zshrc 안에 어디에 적어야 할까요? 맨 아래에 적으면 될까요?
> > > 완전 코린이입니다. 답변 기다리겠습니다 ㅠㅠ
> > 
> > 
> > @tjdrhkd141
> > 안녕하세요. 위의 @hexists 님께서 말씀해주신대로 export 내용은 어디에 적든 상관 없으나 보통 맨 뒷부분에 넣는게 가장 무난하지 않나 싶습니다.
> > 덧붙여, 권한이 없어서 .zshrc 파일이 열리지 않는 경우에는 sudo 명령어를 붙여서 열어보시는 것이 어떨까 싶습니다. 좋은 하루 되세요!
> 
> open ./.zshrc 도 안됐고, sudo를 붙여도 안되어서
> vi로 여니까 편집이 됐습니다 !!
> julu 자바가 아니어도 konlpy가 잘 돌아가네요 !
> 감사합니다 ^^

**Comment by eubinecto** [comment]
안녕하세요,  혹시라도 도움이 될까 싶어 글을 남김니다.
zulu-15 jdk 설치 후, 다음과 같이  `jvmpath`를 직접 설정해주는 방법도 있습니다. 이 경우 굳이 환경변수 설정을 해주지 않아 더 간편하네요.  참고하세요!
```python3
from konlpy.tag import Okt
# zulu - macOS/arm64/version15 설치 이후.
# 해당 path를 지정.
JVM_PATH = '/Library/Java/JavaVirtualMachines/zulu-15.jdk/Contents/Home/bin/java'


def main():
    okt = Okt(jvmpath=JVM_PATH)
    tokens = okt.morphs("으아아아 M1 사용하기 피곤하네")
    print(tokens)


if __name__ == '__main__':
    main()

```

**Comment by ls-jun** [comment]
감사합니다감사합니다감사합니다

**Comment by SeoJuAn** [comment]
zulu-15도 다운 받았고 환경변수 설정도 해줬는데 여전히 [Errno 0] JVM DLL not found: /Library/Java/JavaVirtualMachines/zulu-15.jdk/Contents/Home/bin/java 이 에러가 나는데 어떻게 해결해야 할까요??

**Comment by Scharnhorst93** [comment]
감사합니다. 덕분에 해결되었네요. Zulu 11 버전에선 Zulu 15 버전을 사용했을 때 출력되던 경고 메세지가 표출되지는 않네요.

**Comment by shshjhjh4455** [comment]
> zulu-15도 다운 받았고 환경변수 설정도 해줬는데 여전히 [Errno 0] JVM DLL not found: /Library/Java/JavaVirtualMachines/zulu-15.jdk/Contents/Home/bin/java 이 에러가 나는데 어떻게 해결해야 할까요??

저도 같은 상황이에요

**Comment by EddieKimSeha** [comment]
덕분에 잘 해결했습니다. 감사합니다.

**Comment by eubinean** [comment]
konlpy는 M1에서 잘 안돌아가서 찝찝하고, 배포까지 하자니 까마득하신분들. 
다른 설치도 쉽고 배포도 쉬운 분석기를 쓰는 것도 좋은 방법일 수 있어요. 혹시 궁금하실 수 있으니 몇 개 소개해드릴게요.
- [kiwipiepy](https://github.com/bab2min/kiwipiepy):  C++ 구현체에 파이썬을 래핑한 분석기입니다. M1에서 문제없이 동작합니다.  속도도 konlpy급으로 빠르고, 모호성 해소 정확도도 준수해요.  개발자분도 이슈에 발빠르게 대응해주셔서 여러모로 고마운 라이브러리입니다.
- [pynori](https://github.com/gritmind/python-nori):  엘러스틱서치 검색엔진의 공식 한국어 형태소 분석기로 유명한 nori의 순수 파이썬 포트입니다. M1에서 문제없이 동작합니다. 
- [pecab](https://github.com/hyunwoongko/pecab): nori만큼 유명한 mecab의 순수 파이썬 포트입니다. M1에서 동작합니다.

**Comment by rileyko** [comment]
@SeoJuAn @shshjhjh4455 
저도 같은 경우였는데, libjli.dylib 경로를 지정해주니 해결되었습니다! 아래 내용으로 다시 zrcsh 파일 적용해보시길 바랍니다 !

> #JAVA PATH
> export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-15.jdk/Contents/Home/lib/libjli.dylib
> export PATH=${PATH}:$JAVA_HOME/bin:

참고 : [https://daco2020.tistory.com/348](https://daco2020.tistory.com/348)

**Comment by jundm** [comment]
은인이십니다 ㅠㅠ

**Comment by jundm** [comment]
[eubinecto](https://github.com/eubinecto) 은인이십니다 ㅠㅠ
