### ISSUE TITLE
java,nio.file.InvalidPathException: Illegal char <*> at index 50: ...

### ISSUE THREAD

**Issue by DDadeA** [konlpy/konlpy#367]
`from konlpy.tag import Komoran`
`komoran = Komoran()`
`print(komoran.morphs(u'우왕 코모란도 오픈소스가 되었어요'))`

에러
`Traceback (most recent call last):`
 ` File "Z:\PROJECT\0_py\bbane\main.py", line 2, in <module>`
`    komoran = Komoran()`
`  File "Z:\PROGRAM\Python39\lib\site-packages\konlpy\tag\_komoran.py", line 93, in __init__`
`    jvm.init_jvm(jvmpath, max_heap_size)`
`  File "Z:\PROGRAM\Python39\lib\site-packages\konlpy\jvm.py", line 64, in init_jvm`
`    jpype.startJVM(jvmpath, '-Djava.class.path=%s' % classpath,`
`  File "Z:\PROGRAM\Python39\lib\site-packages\jpype\_core.py", line 227, in startJVM`
`    _jpype.startup(jvmpath, tuple(args),`
`SystemError: java.nio.file.InvalidPathException: Illegal char <*> at index 50: Z:\PROGRAM\Python39\Lib\site-packages\konlpy\java\*`

...\Python39\Lib\site-packages\konlpy\jvm.py 의 32 번째 줄 `'{0}{1}*',` 과 46번째 줄 끝의 `,`, 47번째 줄 `'{0}{1}*'`을 주석처리 해주었더니 잘 작동합니다.

**Comment by DDadeA** [comment]
[https://github.com/konlpy/konlpy/issues/349#issuecomment-817102788](url)
