### ISSUE TITLE
pycharm 에서는 안되고, conda 에서는 잘 됩니다.

### ISSUE THREAD

**Issue by hyemiRyu** [konlpy/konlpy#403]
안녕하세요.

python 도 초보라 도움 없이는 진도가 전혀 나가지 않을 것 같아요ㅠㅠ
conda 에서는 에러 없이 잘 되는데 pycharm 에서는 아래와 같은 에러가 발생하고 있어요
도움을 주셨으면 좋겠습니다.

pycharm 버전 : PyCharm 2021.3.3 (Community Edition)
python version : 3.7
java verion : 18
jpype 1.3.0

소스코드는 아래와 같습니다.

```
from konlpy.tag import Kkma

kkma = Kkma()

text = '아버지가 방에 들어갑니다.'

morphs = kkma.morphs(text)
print(morphs)

```

아래는 에러 문구 입니다.

Traceback (most recent call last):
  File "C:/Users/nrgha/PycharmProjects/pythonProject/token.py", line 1, in <module>
    from konlpy.tag import Kkma
  File "C:\Users\nrgha\anaconda3\envs\chatbot\lib\site-packages\konlpy\__init__.py", line 7, in <module>
    from konlpy.downloader import download
  File "C:\Users\nrgha\anaconda3\envs\chatbot\lib\site-packages\konlpy\downloader.py", line 7, in <module>
    import subprocess
  File "C:\Users\nrgha\anaconda3\envs\chatbot\lib\subprocess.py", line 126, in <module>
    import threading
  File "C:\Users\nrgha\anaconda3\envs\chatbot\lib\threading.py", line 8, in <module>
    from traceback import format_exc as _format_exc
  File "C:\Users\nrgha\anaconda3\envs\chatbot\lib\traceback.py", line 5, in <module>
    import linecache
  File "C:\Users\nrgha\anaconda3\envs\chatbot\lib\linecache.py", line 11, in <module>
    import tokenize
  File "C:\Users\nrgha\anaconda3\envs\chatbot\lib\tokenize.py", line 35, in <module>
    from token import *
  File "C:\Users\nrgha\PycharmProjects\pythonProject\token.py", line 1, in <module>
    from konlpy.tag import Kkma
  File "C:\Users\nrgha\anaconda3\envs\chatbot\lib\site-packages\konlpy\tag\__init__.py", line 6, in <module>
    from konlpy.tag._hannanum import Hannanum
  File "C:\Users\nrgha\anaconda3\envs\chatbot\lib\site-packages\konlpy\tag\_hannanum.py", line 9, in <module>
    from konlpy import jvm, utils
  File "C:\Users\nrgha\anaconda3\envs\chatbot\lib\site-packages\konlpy\jvm.py", line 4, in <module>
    import logging
  File "C:\Users\nrgha\anaconda3\envs\chatbot\lib\logging\__init__.py", line 210, in <module>
    _lock = threading.RLock()
AttributeError: module 'threading' has no attribute 'RLock'

Process finished with exit code 1

![pycharm](https://user-images.githubusercontent.com/7799868/160637989-896599d7-fcd3-4f96-9ffc-a01679d6a9fa.png)

**Comment by hexists** [comment]
@hyemiRyu 
안녕하세요~
해당 오류 내용이 konlpy의 오류보다는 pycharm 설정에 관련된 오류 같습니다.
pycharm을 사용하고 있지 않아 큰 도움을 드리기는 어려울 것 같아요.

먼저 pycharm terminal에서 konlpy가 잘 설치되어 있고, 실행되는지 확인해보시는 건 어떨까요?
<img width="1552" alt="스크린샷 2022-03-30 오후 10 13 52" src="https://user-images.githubusercontent.com/6520567/160842906-c688be8c-331d-411f-a1af-d833c41b56ca.png">

**Comment by hyemiRyu** [comment]
도움 주셔서 감사합니다.  pycharm console 에서는 또 잘 되네요ㅠㅠ
pycharm 을 포기해야 되나봐요

혹시 konlpy 사용 시 주로 사용하는 IDE 가 있을까요? 😄

**Comment by hexists** [comment]
@hyemiRyu 
IDE는 사용자마다 잘 맞는 것을 사용하면 될 것 같습니다^^
해당 이슈는 konlpy 이슈가 아니라서 이슈 닫겠습니다~
감사합니다!
