### ISSUE TITLE
FileNotFoundError occurred in virtualenv python3

### ISSUE THREAD

**Issue by re4lfl0w** [konlpy/konlpy#43]
```bash
(python3)Documents $ pip3 install konlpy
Downloading/unpacking konlpy
  Downloading konlpy-0.4.0.tar.gz (13.4MB): 13.4MB downloaded
  Running setup.py (path:~/.virtualenvs/python3/build/konlpy/setup.py) egg_info for package konlpy
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "~/.virtualenvs/python3/build/konlpy/setup.py", line 59, in <module>
        install_requires=requirements())
      File "~/.virtualenvs/python3/build/konlpy/setup.py", line 14, in requirements
        with open(os.path.join(os.path.dirname(__file__), reqfile)) as f:
    FileNotFoundError: [Errno 2] No such file or directory: '~/.virtualenvs/python3/build/konlpy/requirements-py3.txt'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "~/.virtualenvs/python3/build/konlpy/setup.py", line 59, in <module>

    install_requires=requirements())

  File "~/.virtualenvs/python3/build/konlpy/setup.py", line 14, in requirements

    with open(os.path.join(os.path.dirname(__file__), reqfile)) as f:

FileNotFoundError: [Errno 2] No such file or directory: '~/.virtualenvs/python3/build/konlpy/requirements-py3.txt'

---------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in ~/.virtualenvs/python3/build/konlpy
Storing debug log for failure in ~/.pip/pip.log
```

python 2.x 가상환경에서는 설치가 잘 되네요..

**Comment by iasandcb** [comment]
pip3 install git+git://github.com/konlpy/konlpy.git

로 하면 설치는 됩니다.

**Comment by re4lfl0w** [comment]
@iasandcb 감사합니다. 순한 양처럼 설치가 아주 잘 되네요.

**Comment by e9t** [comment]
이슈 제기 감사합니다.
확인해보니 requirements-py3.txt가 MANIFEST.in에 포함되지 않아서 위 문제가 발생한 것 같네요.
일단 패칭해두었으니 오늘/내일 중으로 버젼 0.4.1 릴리즈하면서 해결되는지 확인해보면 좋을 것 같습니다 :)

**Comment by e9t** [comment]
안녕하세요. 최근 버젼(0.4.2 이상)에서는 위 문제가 해결되었습니다.
일단 이슈를 닫을테니 혹시 같은 문제가 발생한다면 다시 이슈를 열어주시기 바랍니다.
다시 한 번 감사드립니다 :) @re4lfl0w

**Comment by iasandcb** [comment]
이제 잘 됩니다. 고맙습니다. ^^b
