### ISSUE TITLE
konlpy.download('komoran-dic') 했는데도 IOError: Please download komoran-dic: `konlpy.download('komoran-dic')` 발생합니다.

### ISSUE THREAD

**Issue by stray-leone** [konlpy/konlpy#46]
### environment 
 * ubuntu 14.04 64bit
 * python 2.7.6
 * java 1.7.0

아래처럼 komoran-dic을 다운로드 받았는데도,
```python
IOError: Please download komoran-dic: `konlpy.download('komoran-dic')`
>>> import konlpy
>>> konlpy.download('komoran-dic')
KoNLPy downloader
[konlpy_data] Downloading package 'komoran-dic'...
[konlpy_data] Download finished
[konlpy_data] Unzipping file /home/kim/konlpy_data/dictionaries/komoran-dic.zip
Done
```
아래와 같이 또 에러가 나네요.
```python
>>> komoran = Komoran()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/konlpy/tag/_komoran.py", line 78, in __init__
    raise IOError("Please download komoran-dic: `konlpy.download('komoran-dic')`")
IOError: Please download komoran-dic: `konlpy.download('komoran-dic')`
>>>
```

code를 보니깐 interface가 call 안된다고 하는데,
해결하려면, 무엇을 체크해야 할까요.....
```python
except TypeError: # Package kr.lucypark.komoran.KomoranInterface is not Callable
   raise IOError("Please download komoran-dic: `konlpy.download('komoran-dic')`")
```

**Comment by e9t** [comment]
오늘/내일 중 릴리즈될 버젼 0.4.1에서는 komoran dictionary를 konlpy 안에 포함시켰습니다. (해당 커밋: 796c156)
업데이트 이후에도 계속 문제가 발생하는지 확인해주시면 감사하겠습니다.

**Comment by e9t** [comment]
@stray-leone 님, 최근 KoNLPy가 0.4.3으로 버젼업하게 되었습니다. 업그레이드하고도 위 문제가 계속 발생하는지 확인해주실 수 있나요?

    pip install konlpy --upgrade

**Comment by stray-leone** [comment]
@e9t  답이 늦었네요.
정상 동작 합니다 :) 굿!!
