### ISSUE TITLE
버젼 0.4.2를 pip을 통해 whl 파일로 설치시 Python3에서 설치 오류

### ISSUE THREAD

**Issue by e9t** [konlpy/konlpy#50]
원래 Python3에서는 JPype1이 아니라 JPype1-py3 패키지를 설치해야하는데, 설치 로그를 보니 전자로 설치되고 있습니다.

<pre>
epark@dada:~$ pip3 install konlpy --upgrade
Downloading/unpacking konlpy from https://pypi.python.org/packages/2.7/k/konlpy/konlpy-0.4.2-py2.py3-none-any.whl#md5=2b9b2c74d333f1266ee24e39074239d9
  Downloading konlpy-0.4.2-py2.py3-none-any.whl (22.4MB): 22.4MB downloaded
Downloading/unpacking JPype1>=0.5.7 (from konlpy)
  Downloading JPype1-0.5.7.tar.gz (138kB): 138kB downloaded
  Running setup.py (path:/tmp/pip_build_root/JPype1/setup.py) egg_info for package JPype1
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/JPype1/setup.py", line 9, in <module>
        import exceptions
    ImportError: No module named 'exceptions'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/JPype1/setup.py", line 9, in <module>

    import exceptions

ImportError: No module named 'exceptions'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/JPype1
Storing debug log for failure in /home/epark/.pip/pip.log
</pre>

지금은 setup.py 내의 [requirements()](https://github.com/konlpy/konlpy/blob/master/setup.py#L9)를 통해 파이썬 2, 3에 각각 requirements.txt, requirements-py3.txt 를 전달해주고 있는데, 일괄적으로 requirements.txt가 전달되고 있는듯합니다.

**Comment by e9t** [comment]
http://wheel.readthedocs.org/en/latest/ 에 conditional requirements 설정하는 방법이 나오네요.
기존 방법대로 하면 whl 파일을 생성하던 파이썬 인터프리터 버젼에 따라 requirements가 정해져서 (이 경우엔 Python 2) 문제가 생긴듯 합니다.
