### ISSUE TITLE
Hannanum module can't find "ChartMorphAnalyzer.json"

### ISSUE THREAD

**Issue by krkhnh** [konlpy/konlpy#60]
OS: Windows 7
Language: Python 2.7.8
IDE: PyCharm Community Edition 4.5.1
Frameworks: Django 1.7, Virtualenv 12.1.1

Code:

```
def word_count(text):
    h = Hannanum()
    nouns = h.nouns(text)
    return Counter(nouns)
```

`nouns = h.nouns(text)` keep raising an exception as below.

Error:

```
java.io.FileNotFoundException: D:\Hans\CNTT\150323%20onlineTrendAnalysisSolution\PyCharm\web_server\myvenv\Lib\site-packages\konlpy\java\conf\plugin\MajorPlugin\MorphAnalyzer\ChartMorphAnalyzer.json (吏 ?뺣맂 寃쎈줈瑜?李얠쓣 ???놁뒿?덈떎)              
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:146)
        at java.io.FileInputStream.<init>(FileInputStream.java:101)
        at java.io.FileReader.<init>(FileReader.java:58)
        at kr.ac.kaist.swrc.jhannanum.share.JSONReader.<init>(JSONReader.java:48)
        at kr.ac.kaist.swrc.jhannanum.plugin.MajorPlugin.MorphAnalyzer.ChartMorphAnalyzer.ChartMorphAnalyzer.initialize(ChartMorphAnalyzer.java:176)
        at kr.ac.kaist.swrc.jhannanum.hannanum.Workflow.activateWorkflow(Workflow.java:421)
        at kr.lucypark.jhannanum.comm.HannanumInterface.simplePos09(HannanumInterface.java:80)
```

I checked the 'ChartMorphAnalyzer.json' file and it exists on that path. Maybe a spacebar character in the path caused this exception?

I tried `Kkma` and it worked without any problem.

한국어로 말씀해주셔도 됩니다. 혹시나 외국인이 참고할 일이 있을까싶어 영어로 작성했습니다.
##

**Comment by e9t** [comment]
Hannanum의 경우 특성상 데이터 파일 몇 개를 읽어들이는데, 그 때 절대 경로가 사용됩니다.
지금 봐서는 말씀하신대로 경로에 있는 공백이 문제일 수도 있겠지만 확신하기는 어렵네요. 혹시 공백없애고 다시 해보셨나요?

**Comment by e9t** [comment]
@krkhnh 님, 혹시 문제를 해결하셨는지 궁금합니다. 혹시 경로상의 공백을 없애면 문제 없이 작동하나요? 감사합니다 :)

**Comment by krkhnh** [comment]
한번 시도를 해본적이 있지만 확실하지가 않아서 답변을 못드리고 있었습니다.

django를 이용하지 않고 konlpy를 사용하면 띄어쓰기에 상관이 없이 정상작동했습니다. 그리고 django를 이용 시 경로에 공백자가 없으면 정상작동했습니다.

여기에서 미루어보면, django 프레임워크 상에서 konlpy를 이용했을 때 경로상에 공백자가 들어가면 해당 오류가 발생하는게 아닌가... 싶지만 확실히 테스트를 해보기 전엔 확답드리기가 힘듭니다; 기회가 되면 다시 테스트를 해보겠습니다.

**Comment by e9t** [comment]
네 감사합니다. 일단 konlpy 단에서도 해결할 수 있는 버그인 것 같으니 이슈는 열어두도록 하겠습니다.

**Comment by e9t** [comment]
이 이슈는 1년 이상 업데이트가 없으므로 닫도록 하겠습니다.
혹시 동일한 증상을 겪는 분이 있다면 이 이슈를 refer하면서 새 이슈를 열어주시기 바랍니다.
