### ISSUE TITLE
Hannanum produces JSONException on Windows

### ISSUE THREAD

**Issue by e9t** [konlpy/konlpy#7]
>>> Hannanum().nouns(u'테스트')
    org.json.JSONException: Unterminated string at 101 [character 22 line 6]
        at org.json.JSONTokener.syntaxError(JSONTokener.java:423)
        at org.json.JSONTokener.nextString(JSONTokener.java:249)
        at org.json.JSONTokener.nextValue(JSONTokener.java:349)
        at org.json.JSONObject.<init>(JSONObject.java:209)
        at org.json.JSONTokener.nextValue(JSONTokener.java:352)
        at org.json.JSONArray.<init>(JSONArray.java:125)
        at org.json.JSONTokener.nextValue(JSONTokener.java:356)
        at org.json.JSONObject.<init>(JSONObject.java:209)
        at org.json.JSONObject.<init>(JSONObject.java:310)
        at kr.ac.kaist.swrc.jhannanum.share.JSONReader.<init>(JSONReader.java:55)
        at kr.ac.kaist.swrc.jhannanum.plugin.MajorPlugin.MorphAnalyzer.ChartMorphAnalyzer.ChartMorphAnalyzer.initialize(ChartMorphAnalyzer.java:176)
        at kr.ac.kaist.swrc.jhannanum.hannanum.Workflow.activateWorkflow(Workflow.java:421)
        at kr.lucypark.jhannanum.comm.HannanumInterface.extractNoun(HannanumInterface.java:50)

**Comment by e9t** [comment]
Fixed with bc75ca8fcf89fcd01e10d299f77df2e94891bad8
