### ISSUE TITLE
Mecab compile error

### ISSUE THREAD

**Issue by purblue10** [konlpy/konlpy#79]
When I call "mecab = Mecab()", I got the below error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/konlpy/tag/_mecab.py", line 102, in __init__
    self.tagger = Tagger('-d %s' % dicpath)
NameError: name 'Tagger' is not defined
```

How should I handle with the error? I used OS X El Capitan.

**Comment by e9t** [comment]
Hi! You have to install it separately, as seen in the installation documents: http://konlpy.org/en/latest/install/.

Please note that `Mecab` is not supported for Windows.
